env:
    # Config
    CONFIG: config.sh

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "TWRP Build"
  timeout_in: 90m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 7
      memory: 28G

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/twrp/reposync.sh)"
      
  DT_Clone_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/RMX3461/dtclone.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/RMX3461/building.sh)"

  Upload_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/RMX3461/uploading.sh)"
