env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "PBRP Build"
  timeout_in: 90m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Repo Sync_script:
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/pbrp/reposync.sh | bash
      
  Device Tree Cloning_script:
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/pbrp/dtclone.sh | bash

  Building_script:
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/pbrp/building.sh | bash

  Uploading_script:
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/uploading.sh | bash
